### ISSUE TITLE
Bug: Some Dev Console Commands don't work

### ISSUE THREAD

**Issue by MoistenedEgg** [CatRass/SchlattCoin#5] opened 2021-03-14 10:56 UTC
The moneyGive, coinGive and investorGive commands do not work at all.

On a side note:
investorGive needs a more descriptive name and description

**Comment by CatRass** [comment] 2021-03-15 08:34
Console was fixed. the issue was mainly caused by the addon being for engine 3.2.3, and exporting in 3.2.1 caused some issues. Will be fixed in next release

**Closed as completed by CatRass** 2021-03-15 08:34 UTC
Labels: Bug, v0.1.2
